#server_addr = "127.0.0.1"
server_addr = "223.254.130.92"
server_port = 8000
log_level = "info"
heartbeat_interval = 30
heartbeat_timeout = 60

[[proxies]]
name = "test-tcp"
kind = "tcp"
local_ip = "127.0.0.1"
local_port = 18880
remote_port = 28880

[web_server]
addr = "127.0.0.1"
port = 8000
user = "admin"
password = "admin"

[tls]
enabled = false
ca_cert_path = "./certificates/ca-cert.pem"
insecure_skip_verify = true