server_addr = "127.0.0.1"
server_port = 8000
log_level = "info"

[[proxies]]
name = "test-tcp"
kind = "tcp"
local_ip = "127.0.0.1"
local_port = 18880
remote_port = 28880

[web_server]
addr = "127.0.0.1"
port = 8000
user = "admin"
password = "admin"