[package]
name = "rystra-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rystra-model = { path = "../rystra-model" }
tokio.workspace = true
async-trait.workspace = true